### PR TITLE
Removed robosub msgs and moved to robosub_msgs

### PR DESCRIPTION
**Pull request by ryan-summers**
All messages moved to robosub_msgs repository.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/126)

### CODE REVIEW

**Comment by skallaher** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 18 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/126#-L5en0jcpdWURMXkEFF7:-L5en0jcpdWURMXkEFF8:b-vjsyfb) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/5615fe84a159ac9ccd7c51fb71b5105576d3c036/CMakeLists.txt#L18)):*
> ```CMake
>     std_msgs
>     message_generation
>     robosub
> ```

Does the simulator still depend on `robosub` after this change?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/126)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[CMakeLists.txt, line 18 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/126#-L5en0jcpdWURMXkEFF7:-L5j1cjqSMG8ZseC2203:b-7y8qhr) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/5615fe84a159ac9ccd7c51fb71b5105576d3c036/CMakeLists.txt#L18)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Does the simulator still depend on `robosub` after this change?
</blockquote></details>

Yes, our launch files still require the robosub nodes to run.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/126)*

**Comment by skallaher** [comment]
@ryan-summers, the `.travis.yml` file needs to be updated to include the `robosub_msgs` package so that it can be built with them.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/126#-:-L6NYyCXtDY7x8d9S1mB:bem8852)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/126)*

**Pull request merged**
