### PR TITLE
Modified camera lens to use values gathered from calibrations.

### PR DESCRIPTION
**Pull request by skallaher**
Cameras should now have more accurate distortion compared to real cameras.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/51)

### CODE REVIEW

**Comment by bkallaher** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[models/cobalt/model.sdf, line 549 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/51#-Kay3tvVvkSbt7RHiAzG:-Kay3tvVvkSbt7RHiAzH:b-rml5mr) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/7d8db4b82f256105c577bb35e1799d01539a2057/models/cobalt/model.sdf#L549)):*
> ```
>                   <type>custom</type>
>                   <custom_function>
>                       <c1>691.5</c1>   
> ```

Could you add a comment describing what these numbers mean and how they were derived

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/51)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/51#-:-Kay59Nm7ZKfJMMlaxVk:bnfp4nl)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[models/cobalt/model.sdf, line 549 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/51#-Kay3tvVvkSbt7RHiAzG:-Kay5HiTezo6-aZZSHmO:b-vjrbud) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/7d8db4b82f256105c577bb35e1799d01539a2057/models/cobalt/model.sdf#L549)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Could you add a comment describing what these numbers mean and how they were derived
</blockquote></details>

Perhaps this information might be better suited to be in the wiki?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/51)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[models/cobalt/model.sdf, line 549 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/51#-Kay3tvVvkSbt7RHiAzG:-KayVglM0iMnrcnNho1m:b-gnta0b) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/7d8db4b82f256105c577bb35e1799d01539a2057/models/cobalt/model.sdf#L549)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Perhaps this information might be better suited to be in the wiki?
</blockquote></details>

Agreed. The necessary explanation would not suit comments very well. Where on the wiki do you suggest?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/51)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[models/cobalt/model.sdf, line 549 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/51#-Kay3tvVvkSbt7RHiAzG:-Kb8TXxpjCLHGzFbt7yu:b-gfn83g) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/7d8db4b82f256105c577bb35e1799d01539a2057/models/cobalt/model.sdf#L549)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Agreed. The necessary explanation would not suit comments very well. Where on the wiki do you suggest?
</blockquote></details>

OK

some section under vision or cameras?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/51)*

**Pull request merged**
