### PR TITLE
Linking against robosub libs and headers

### LINKED ISSUE #74: Link to Robosub libraries
There are some classes/libraries in the PalouseRobosub/robosub repository that we depend on (like serial, throttled_publisher, etc.) that up till now we have been copying and duplicating the files into this repository. The issue is that we loose out on bug fixes unless we change both copies of the file. We should be able to get this project to link to the robosub shared libraries.

### PR DESCRIPTION
**Pull request by bkallaher**
Fixes #74

This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/77)

### CODE REVIEW

**Comment by bkallaher** [comment]
The build will fail until the corresponding PR is merged in the main repo

**Comment by dcrossman** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/77#-:-Ke_wRhZVtLhWKVtK4Cw:bnfp4nl)*

**Comment by irwineffect** [comment]
Reviewed 6 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/77)*

**Comment by irwineffect** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/77#-:-Kea1OAuBEnl3f6sssQO:bnfp4nl)*

**Pull request merged**
