### PR TITLE
New models

### PR DESCRIPTION
**Pull request by bkallaher**
Added SDF for remaining models. Solves #9

### CODE REVIEW

**Comment by bkallaher** [comment]
Just don't have the cover for the torpedo task.

**Comment by skallaher** [comment]
Could you put them in the world so that the launch file opens with them in the right places?

**Review by skallaher — CHANGES_REQUESTED** [review]
The torpedo target doesn't have holes in it.

**Comment by skallaher** [comment]
Also, while you're messing with the models, the pool has a color of `Gazebo/Gray` which is not valid (at least for me) so it shows up as white. The spelling used is actually `Gazebo/Grey` I haven't found something for the `Gazebo/LightGray` occurrences yet, though we can always make our own.

**Review by dcrossman — CHANGES_REQUESTED** [review]
Looks good! It would be nice if they were placed in the world. I'm not sure that the torpedo board really needs holes right now. I think that might be a bitch to do with only sdf. It'll probably require a mesh.

**Comment by skallaher** [comment]
Are there plans to use a mesh for the sub at some point?

**Comment by dcrossman** [comment]
A mesh for the sub could pretty much be added anytime. The mesh file itself would have to be added with git lfs though.

**Comment by skallaher** [comment]
@BigDCross, I am seeing that the Gazebo/LightGray material doesn't exist, is this just on my end?

**Comment by dcrossman** [comment]
Nope. If you remove the material field completely from the pool.sdf it stops that warning actually. I think it gets confused taking materials from both the dae and the sdf.

**Comment by dcrossman** [comment]
Actually you can make the pool itself look better if you manually change the color tags that are in the pool.dae file. @bkallaher  do you want me to commit a couple pool changes?

**Comment by skallaher** [comment]
I'm trying my hand at blender again to see if I can make a mesh for the torpedo target. We'll see how this goes...

**Comment by bkallaher** [comment]
There is no reason for the torpedo target to have holes. Any collada file that you make will have the wrong coloring no matter what you do. All the vision processing should need is the yellow board and the red outlines for the holes.

**Comment by irwineffect** [comment]
But what if we want to shoot simulated torpedoes? :stuck_out_tongue:

**Comment by dcrossman** [comment]
We totally could simulate torpedoes I think. Also the new model looks good Sean. And the colors seem fine on my end.

**Comment by bkallaher** [comment]
The red outlining is too thin. Board is too thick. Collision box won't let the torpedoes through the holes. Colors need to be diffused.

**Comment by skallaher** [comment]
The outlining is per the specifications [here](http://www.robonation.org/sites/default/files/RoboSub_2016_Final_Mission%20and%20Scoring.pdf) of 2.5cm.

**Comment by dcrossman** [comment]
Good point. I would change the collision tag to use the mesh as well.

**Comment by bkallaher** [comment]
That is not 2.5 cm.
screenshot from 2016-12-16 11 44 03

**Comment by skallaher** [comment]
Odd.... you're right. I thought I had them at 2.5, turns out their 1.2 or so. I will fix them shortly

**Comment by bkallaher** [comment]
Light anything is not a color option in SDF.

**Comment by skallaher** [comment]
I'm having some weird issue with faces disappearing when I export to a collada.

**Comment by bkallaher** [comment]
Models have been added to the world!

**Review by skallaher — APPROVED** [review]

**Comment by skallaher** [comment]
Looks good! Now, who wants to do the tower model? :stuck_out_tongue:

**Comment by bkallaher** [comment]
That model was a specific model for last year. We'll add it if it shows up again upon receiving the rules.

**Review by dcrossman — APPROVED** [review]

**Comment by dcrossman** [comment]
Looks good!

**Pull request merged**
