### PR TITLE
added script for toggling the start switch

### PR DESCRIPTION
**Pull request by irwineffect**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/100)

### CODE REVIEW

**Comment by Sindorman** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/100#-:-KwIcb-jLJlXSnGIxOYd:bnfp4nl)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[scripts/start_switch.py, line 14 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/100#-KwJP9V1airhsM-gr8CO:-KwJP9V2vFI65FzmC843:ba3o668) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/579c31465525ca499cb365468db234cb8b8991f7/scripts/start_switch.py#L14)):*
> ```Python
> 
>     rospy.sleep(1)
> ```

Extra whitespace line here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/100)*

**Comment by irwineffect** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[scripts/start_switch.py, line 14 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/100#-KwJP9V1airhsM-gr8CO:-KwqsRBffrV2-GCY8f6Q:b-896fix) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/579c31465525ca499cb365468db234cb8b8991f7/scripts/start_switch.py#L14)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Extra whitespace line here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/100)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/100#-:-Kwr1IXVPD1k3hmGgXj5:bnfp4nl)*

**Pull request merged**
