### PR TITLE
Gibb Pool!!!

### PR DESCRIPTION
**Pull request by bkallaher**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/60)

### CODE REVIEW

**Comment by irwineffect** [comment]
Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[launch/gazebo.launch, line 13 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/60#-KcA_ZVlQbkfw5fHRJF6:-KcA_ZVmgKoCf-gc2rIo:bf2tt90) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/0c576b6ad96bc423640356ee942e5079dbf8dd6d/launch/gazebo.launch#L13)):*
> ```XML
>    <arg name="gui" value="$(arg gui)" />
>    <arg name="verbose" value="true"/>
>    <arg name="world_name" value="$(find robosub_simulator)/worlds/$(arg world_file)"/>
> ```

can we change the "world_file" to just be "world", and then have this be
```xml
<arg name="world_name" value="$(find robosub_simulator)/worlds/$(arg world).world"/>
```

It makes the remapping a bit easier to type out, and world_file isn't intuitive because it doesn't actually want a path to a file, it wants a file name inside of our worlds/folder

---

*[models/gibb/model.config, line 8 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/60#-KcAZ79renSu7R-Jvmck:-KcAZ79renSu7R-Jvmcl:b-v0hoqy) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/0c576b6ad96bc423640356ee942e5079dbf8dd6d/models/gibb/model.config#L8)):*
> ```
>     <author>
>         <name>Dustin Crossman</name>
>         <email>dustin.crossman@gmail.com</email>
> ```

Did Dustin make this, or did Brandon?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/60)*

**Comment by bkallaher** [comment]
Review status: 3 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[launch/gazebo.launch, line 13 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/60#-KcA_ZVlQbkfw5fHRJF6:-KcGybABQtF4qaoNab26:b-bu91xm) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/0c576b6ad96bc423640356ee942e5079dbf8dd6d/launch/gazebo.launch#L13)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

can we change the "world_file" to just be "world", and then have this be
```xml
<arg name="world_name" value="$(find robosub_simulator)/worlds/$(arg world).world"/>
```

It makes the remapping a bit easier to type out, and world_file isn't intuitive because it doesn't actually want a path to a file, it wants a file name inside of our worlds/folder
</blockquote></details>

Updated

---

*[models/gibb/model.config, line 8 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/60#-KcAZ79renSu7R-Jvmck:-KcGygVOoc-nsjNUkXeX:b-bu91xm) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/0c576b6ad96bc423640356ee942e5079dbf8dd6d/models/gibb/model.config#L8)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Did Dustin make this, or did Brandon?
</blockquote></details>

Updated

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/60)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/60#-:-KcUI-WremzHiVpIJghi:bnfp4nl)*

**Comment by irwineffect** [comment]
Reviewed 1 of 7 files at r1, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/60)*

**Pull request merged**
