### PR TITLE
Adds in Casino-themed Props for the 2018 Competition

### PR DESCRIPTION
**Pull request by ryan-summers**
I've added a new world for the 2018 season and added models for the crooked path, modified start gate, dice, and roulette wheel. We should start working with this for future AI development.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/108)

### CODE REVIEW

**Comment by ryan-summers** [comment]
Below is a view of the new map. The roulette wheel is shown as square so that I could get the texture to properly map to the object. It only really has a cylindrical collision box.
new-map

The start gate colors are weird in the prelim rules (it shows it as a light blue). Thoughts?
start-gate

I think the dice and the crooked path turned out rather nice!
dice-task

**Comment by Sindorman** [comment]
OK, from brief look it seems legitimate, however do not take my feedback only. I would want to hear thoughts from James or Sean. @skallaher @irwineffect ?

---

Reviewed 16 of 19 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-:-L1dtFA-UyOVJvUNLb_l:b-96sdeo)*

**Comment by Sindorman** [comment]
I have retained the branch and tested it with new AI. Everything is working good. :lgtm: 

---

Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-:-L3255v3JvPamiurdFv2:b-lkq0eh)*

**Comment by skallaher** [comment]
Reviewed 15 of 19 files at r1, 2 of 3 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[models/2018/dice/dice.sdf, line 1 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L35kW2LyKofboOa7wQm:-L35kW2LyKofboOa7wQn:brieo05) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/0c8dfb2328f9461488dfa5cff6c2fe431a2946b8/models/2018/dice/dice.sdf#L1)):*
> ```
> <?xml version='1.0'?>
> ```

It would be interesting to find out if it is possible to randomize the location of the dice within a field on loading the world. There could also just be a tool script to do this.

---

*[models/2018/dice/dice.sdf, line 14 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L35kkzop1CAkN53Q1_m:-L35kkzop1CAkN53Q1_n:b-96j3ji) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/0c8dfb2328f9461488dfa5cff6c2fe431a2946b8/models/2018/dice/dice.sdf#L14)):*
> ```
>         <geometry>
>           <box>
>             <size>0.3 0.3 0.3</size>
> ```

Last Dave posted on the forums, they were thinking of making the dice 9" square. These are just under 1'.

---

*[models/2018/path_markers/model.config, line 3 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L35lo3JU1tY2IS0f2aF:-L35lo3JU1tY2IS0f2aG:brtdtay) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/0c8dfb2328f9461488dfa5cff6c2fe431a2946b8/models/2018/path_markers/model.config#L3)):*
> ```
> <?xml version="1.0" ?>
> <model>
>     <name>Crooked Path Marker</name>
> ```

You have spaces in your name here, but not in the `CasinoGate` name, could you change them to be consistent?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108)*

**Comment by Sindorman** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[models/2018/dice/dice.sdf, line 1 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L35kW2LyKofboOa7wQm:-L37SLTQkVxV7C-72xWQ:b95ocnl) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/0c8dfb2328f9461488dfa5cff6c2fe431a2946b8/models/2018/dice/dice.sdf#L1)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

It would be interesting to find out if it is possible to randomize the location of the dice within a field on loading the world. There could also just be a tool script to do this.
</blockquote></details>

But wouldn't dice always be in same locations on competition?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108)*

**Comment by ryan-summers** [comment]
Review status: 20 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[models/2018/dice/dice.sdf, line 1 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L35kW2LyKofboOa7wQm:-L3FdAdFV5nDAJ_lDe50:bke0b1k) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/0c8dfb2328f9461488dfa5cff6c2fe431a2946b8/models/2018/dice/dice.sdf#L1)):*
<details><summary><i>Previously, Sindorman (Mykhailo Bykhovtsev) wrote…</i></summary><blockquote>

But wouldn't dice always be in same locations on competition?
</blockquote></details>

This would be something for a future pull request and not this one, I don't think that's really in scope, as it's not specified that they will be random by the competition.

---

*[models/2018/dice/dice.sdf, line 14 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L35kkzop1CAkN53Q1_m:-L3FdHldUhI8VJw5S-2q:b-786koc) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/0c8dfb2328f9461488dfa5cff6c2fe431a2946b8/models/2018/dice/dice.sdf#L14)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Last Dave posted on the forums, they were thinking of making the dice 9" square. These are just under 1'.
</blockquote></details>

Yeah, but nothing has been posted on official dimensions yet. I'll throw them down to 9 inches.

---

*[models/2018/path_markers/model.config, line 3 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L35lo3JU1tY2IS0f2aF:-L3FdxngKjuNeDbJf5nv:bz3aa9i) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/0c8dfb2328f9461488dfa5cff6c2fe431a2946b8/models/2018/path_markers/model.config#L3)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

You have spaces in your name here, but not in the `CasinoGate` name, could you change them to be consistent?
</blockquote></details>

Yep, I'll add spaces to Casino Gate

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108)*

**Comment by skallaher** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[models/2018/dice/dice.sdf, line 1 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L35kW2LyKofboOa7wQm:-L3FeRqWk_VhlXwgaTwx:bhft4e5) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/0c8dfb2328f9461488dfa5cff6c2fe431a2946b8/models/2018/dice/dice.sdf#L1)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

This would be something for a future pull request and not this one, I don't think that's really in scope, as it's not specified that they will be random by the competition.
</blockquote></details>

From a [post by Dave on the forums](http://www.robonation.org/forum/2018-robosub-draft-tasks-now-available-review):
```
Shoot Craps

Randomized dice locations (x,y and height).  Field size TBD (suggestions).  You will receive points for touching any buoy (the points will only count once, so if you hit three buoys, you will only get points for touching one buoy).  If the last two buoys you touch add up to 7, you will receive more points.  If the last two buoys you touch add up to 11, you will receive even more points.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108)*

**Comment by Sindorman** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-:-L3Ff4T71uIHBB8e6JxD:bnfp4nl)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L3PTipDFSg7_fk3_Mha:-L3PTipDFSg7_fk3_Mhb:b-3ixkbu) (no related file):*
@skallaher Should we have the binary files using git lfs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L3PTipDFSg7_fk3_Mha:-L3PU2ez-tv_OSmP_k0W:b-3zwn24) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

@skallaher Should we have the binary files using git lfs?
</blockquote></details>

Good point, probably should.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108)*

**Comment by ryan-summers** [comment]
Review status: 14 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L3PTipDFSg7_fk3_Mha:-L3y2J5PzM4S2xbXLchc:b-lvs435) (no related file):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Good point, probably should.
</blockquote></details>

They have been moved to Git LFS. For reference, the files were only 37KiB.

---

*[models/2018/dice/dice.sdf, line 1 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L35kW2LyKofboOa7wQm:-L3y2QmN-zrfUrcoZVrf:b-896fix) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/0c8dfb2328f9461488dfa5cff6c2fe431a2946b8/models/2018/dice/dice.sdf#L1)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

From a [post by Dave on the forums](http://www.robonation.org/forum/2018-robosub-draft-tasks-now-available-review):
```
Shoot Craps

Randomized dice locations (x,y and height).  Field size TBD (suggestions).  You will receive points for touching any buoy (the points will only count once, so if you hit three buoys, you will only get points for touching one buoy).  If the last two buoys you touch add up to 7, you will receive more points.  If the last two buoys you touch add up to 11, you will receive even more points.
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108)*

**Comment by skallaher** [comment]
Reviewed 9 of 9 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[.gitattributes, line 1 at r5](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L3yZ0kwWZrbOAhpxQn_:-L3yZ0kwWZrbOAhpxQna:b-40k18l) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/216f3b9aa8bfc00a7daf66bb7f834cb3d257464c/.gitattributes#L1)):*
> ```
>  filter=lfs diff=lfs merge=lfs -text
> ```

What is this filter for?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108)*

**Comment by ryan-summers** [comment]
Review status: 22 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[.gitattributes, line 1 at r5](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L3yZ0kwWZrbOAhpxQn_:-L3yuoo7ATLy8TMoc74C:b9rg1zz) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/216f3b9aa8bfc00a7daf66bb7f834cb3d257464c/.gitattributes#L1)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

What is this filter for?
</blockquote></details>

Git automatically added it and forgot to delete it (we believe its a bug when you 'untrack' a file type). It has been removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108#-L3PTipDFSg7_fk3_Mha:-L3ywi3FSM0xDNmeB-2s:bmxilld) (no related file):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

They have been moved to Git LFS. For reference, the files were only 37KiB.
</blockquote></details>

:LGTM:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/108)*

**Pull request merged**
