### PR TITLE
added scripts to jump the sub around the pool

### PR DESCRIPTION
**Pull request by irwineffect**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/62)

### CODE REVIEW

**Comment by bkallaher** [comment]
Some of the comments in the files are inaccurate. For example jump_bins.sh somehow jumps the sub in front of the buoys?

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/62#-:-Kc_0Hyo96go3Q9b6O2V:bubwt2z)*

**Comment by dcrossman** [comment]
Yea scripts work but comments are incorrect.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/62#-:-Kcz7tDy66dzzPBxOIlQ:b-667s6d)*

**Comment by bkallaher** [comment]
:lgtm:

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/62#-:-Kd3AJY3_RrPbTnE9iyG:bnfp4nl)*

**Comment by bkallaher** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/62)*

**Pull request merged**
