### PR TITLE
Updated simulator to use new imu architures with intermediate imu node

### PR DESCRIPTION
**Pull request by irwineffect**
Dependent on PalouseRobosub/robosub#262

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/95)

### CODE REVIEW

**Comment by ryan-summers** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[launch/gazebo.launch, line 29 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95#-KoPQ1jdEPRks4Uff_00:-KoPQ1jdEPRks4Uff_01:bt1l57u) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/f999f0cca6d47f745156721863e91c059d411bd3/launch/gazebo.launch#L29)):*
> ```XML
>   </node>
>   <node name="thruster" pkg="robosub" type="delayed_node.sh" args="3 thruster_maestro"/>
>   <node name="bno055_left" pkg="robosub" type="bno055_sensor" launch-prefix="$(find robosub)/scripts/sleepme.sh 3"/>
> ```

What is sleepme.sh ? I didn't see it added in the other commit. You should use the delayed_node.sh

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95)*

**Comment by bkallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[launch/gazebo.launch, line 29 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95#-KoPQ1jdEPRks4Uff_00:-KoPRjS85CQoWpcSyVuH:b17uj66) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/f999f0cca6d47f745156721863e91c059d411bd3/launch/gazebo.launch#L29)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

What is sleepme.sh ? I didn't see it added in the other commit. You should use the delayed_node.sh
</blockquote></details>

It has been merged into dev from another branch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95)*

**Comment by irwineffect** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[launch/gazebo.launch, line 29 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95#-KoPQ1jdEPRks4Uff_00:-KoPe1oMW4AHh6WoVMhI:bqzhkgs) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/f999f0cca6d47f745156721863e91c059d411bd3/launch/gazebo.launch#L29)):*
<details><summary><i>Previously, bkallaher (Brandon Kallaher) wrote…</i></summary><blockquote>

It has been merged into dev from another branch.
</blockquote></details>

Brandon is correct, it got merged in earlier today. `sleepme.sh` is required because it properly forwards the roslaunch remapping arguments, `delayed_node.sh` does not (i.e. it doesn't remap the node name properly). `delayed_node.sh` is now considered deprecated, but it's still around for legacy purposes for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95)*

**Comment by skallaher** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[launch/gazebo.launch, line 29 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95#-KoPQ1jdEPRks4Uff_00:-KoQ6hl7DEnR9zGr-ap5:b-chosyf) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/f999f0cca6d47f745156721863e91c059d411bd3/launch/gazebo.launch#L29)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Brandon is correct, it got merged in earlier today. `sleepme.sh` is required because it properly forwards the roslaunch remapping arguments, `delayed_node.sh` does not (i.e. it doesn't remap the node name properly). `delayed_node.sh` is now considered deprecated, but it's still around for legacy purposes for now.
</blockquote></details>

I prefer this over `delayed_node.sh` anyways because it lists the node name as the node that is run rather than have it in the arguments.

---

*[scripts/create_sensor_vsp.sh, line 12 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95#-KoQ7DjInyasMZAeOa_p:-KoQ7DjInyasMZAeOa_q:b-virnpb) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/f999f0cca6d47f745156721863e91c059d411bd3/scripts/create_sensor_vsp.sh#L12)):*
> ```Shell
> 
> # Override parameters to the virtual serial ports.
> rosparam set /ports/bno055_left $port_to_sensors
> ```

How will this work with multiple IMUs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[launch/gazebo.launch, line 29 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95#-KoPQ1jdEPRks4Uff_00:-KoSu3HkYeb1FRxwLkb-:b4pke3r) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/f999f0cca6d47f745156721863e91c059d411bd3/launch/gazebo.launch#L29)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

I prefer this over `delayed_node.sh` anyways because it lists the node name as the node that is run rather than have it in the arguments.
</blockquote></details>

Ah, I forgot we use origin/dev as our master branch. Can we please change this? It's confusing as all hell that our repo uses origin/dev as the master branch...

---

*[scripts/create_sensor_vsp.sh, line 12 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95#-KoQ7DjInyasMZAeOa_p:-KoSuJ12-ARqkjCb2U9d:b-1x0ea0) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/f999f0cca6d47f745156721863e91c059d411bd3/scripts/create_sensor_vsp.sh#L12)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

How will this work with multiple IMUs?
</blockquote></details>

It's not really supposed to. The simulator only uses a singular IMU (bno055_left) in the launch. It then outputs the data to the simulated serial port for the left. In the future, we may want to add multiple simulated IMU support to the simulator, but that isn't in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95)*

**Comment by skallaher** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[scripts/create_sensor_vsp.sh, line 12 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95#-KoQ7DjInyasMZAeOa_p:-KoToeCVtdEV6eNvQntM:b-kzgqyf) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/f999f0cca6d47f745156721863e91c059d411bd3/scripts/create_sensor_vsp.sh#L12)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

It's not really supposed to. The simulator only uses a singular IMU (bno055_left) in the launch. It then outputs the data to the simulated serial port for the left. In the future, we may want to add multiple simulated IMU support to the simulator, but that isn't in this PR.
</blockquote></details>

OK. I just wanted to make sure it had been thought about.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95#-:-KoTonWr85D5CDy6Xgqb:bnfp4nl)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/95)*

**Pull request merged**
