### PR TITLE
Linear accel topic

### PR DESCRIPTION
**Pull request by dcrossman**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/52)

### CODE REVIEW

**Comment by irwineffect** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[models/cobalt/model.sdf, line 197 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KayKF-D1GgHB8wMo-rD:-KayKF-D1GgHB8wMo-rE:bb4mn7s) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/69880405a7318d7be6d5fcf646a53f02038bae83/models/cobalt/model.sdf#L197)):*
> ```
>       <sensor name="imu" type="imu">
>         <imu>
>           <topic>rs_lin_accel_data</topic>
> ```

probably want to change this to a less gross name, like acceleration/linear

---

*[src/simulator_bridge.cpp, line 175 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KayJnj7RUV-OFND1Etq:-KayJnj8ILKOAFrtCL2q:b-4tonmz) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/69880405a7318d7be6d5fcf646a53f02038bae83/src/simulator_bridge.cpp#L175)):*
> ```cpp
>     position_msg.x -= pinger_position[0];
>     position_msg.y -= pinger_position[1];
>     position_msg.z -= pinger_position[2];
> ```

Since we can know absolute depth, what're people's thoughts on not having Z being relative to the pinger?

---

*[src/simulator_bridge.cpp, line 259 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KayKjpniNNNd1N6edaO:-KayKjpniNNNd1N6edaP:b-h0nql8) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/69880405a7318d7be6d5fcf646a53f02038bae83/src/simulator_bridge.cpp#L259)):*
> ```cpp
>     hydrophone_deltas_pub = nh.advertise<robosub::HydrophoneDeltas>(
>             "hydrophones/30khz/delta", 1);
>     lin_accel_pub = nh.advertise<geometry_msgs::Vector3Stamped>("rs_lin_accel_data", 1);
> ```

topic: acceleration/linear

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52)*

**Comment by bkallaher** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[models/cobalt/model.sdf, line 197 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KayKF-D1GgHB8wMo-rD:-Kazr4XC5p_kyJrwYias:bvp4ak4) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/69880405a7318d7be6d5fcf646a53f02038bae83/models/cobalt/model.sdf#L197)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

probably want to change this to a less gross name, like acceleration/linear
</blockquote></details>

I agree with James.

---

*[models/cobalt/model.sdf, line 220 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KazrBfJheCNKcnxvB7f:-KazrBfJheCNKcnxvB7g:b-edidm5) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/69880405a7318d7be6d5fcf646a53f02038bae83/models/cobalt/model.sdf#L220)):*
> ```
>         </imu>
>         <always_on>1</always_on>
>         <update_rate>33</update_rate>
> ```

Why 33 for an update rate? I'm assuming this is in Hertz.

---

*[src/simulator_bridge.cpp, line 175 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KayJnj7RUV-OFND1Etq:-KazrVgE_1lv_SM3Jr8V:bc1jep3) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/69880405a7318d7be6d5fcf646a53f02038bae83/src/simulator_bridge.cpp#L175)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Since we can know absolute depth, what're people's thoughts on not having Z being relative to the pinger?
</blockquote></details>

At some point we will need to correlate the two to say that the pinger is at a specific depth. But yes the z position should be absolute from the depth sensors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52)*

**Comment by irwineffect** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52)*

**Comment by dcrossman** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[models/cobalt/model.sdf, line 197 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KayKF-D1GgHB8wMo-rD:-KbCL0jOC89y45zScq6i:b-9v0fck) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/69880405a7318d7be6d5fcf646a53f02038bae83/models/cobalt/model.sdf#L197)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

I agree with James.
</blockquote></details>

This is all commented anyway so I'll be removing this bit. The topic is actually set in the simulator bridge.

---

*[models/cobalt/model.sdf, line 220 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KazrBfJheCNKcnxvB7f:-KbCKlRllrBcoCLTdB6g:b-zgevld) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/69880405a7318d7be6d5fcf646a53f02038bae83/models/cobalt/model.sdf#L220)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Why 33 for an update rate? I'm assuming this is in Hertz.
</blockquote></details>

I set it to 33 since it was roughly the update rate of the real bno imu, though that may have changed. Do you know if it has?

---

*[src/simulator_bridge.cpp, line 175 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KayJnj7RUV-OFND1Etq:-KbCLIRO0VihBtjOeKVt:b-kvx5w4) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/69880405a7318d7be6d5fcf646a53f02038bae83/src/simulator_bridge.cpp#L175)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

At some point we will need to correlate the two to say that the pinger is at a specific depth. But yes the z position should be absolute from the depth sensors.
</blockquote></details>

Ok. I'll just make it absolute depth.

---

*[src/simulator_bridge.cpp, line 259 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KayKjpniNNNd1N6edaO:-KbCLLd5aRc9DYHmoKAq:b-896fja) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/69880405a7318d7be6d5fcf646a53f02038bae83/src/simulator_bridge.cpp#L259)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

topic: acceleration/linear
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52)*

**Comment by dcrossman** [comment]
Review status: 2 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[models/cobalt/model.sdf, line 798 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KbCNUSay2mnXGP1xJRA:-KbCNUSbccsjn-OuVF4I:b-i99m4a) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/8e8570caf627ae680483418c0b1fac35900b08f1/models/cobalt/model.sdf#L798)):*
> ```
>       <serviceName>gazebo/rs_imu_service</serviceName>
>       <gaussianNoise>0.0</gaussianNoise>
>       <updateRate>20.0</updateRate>
> ```

The bno's update rate is set to 20 in cobalt.param.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52)*

**Comment by bkallaher** [comment]
Reviewed 1 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52)*

**Comment by dcrossman** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[param/simulator.yaml, line 6 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KbCT-Ef1AL-n88vMm3v:-KbCT-EgOtbU0N_CEkzG:b-w98n3u) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/8e8570caf627ae680483418c0b1fac35900b08f1/param/simulator.yaml#L6)):*
> ```YAML
>     visualize_thrusters: true
>     visualizer_update_rate: 10
>     bridge_rate: 33 # Roughly same as bno update rate
> ```

Ok so this is currently the global bridge rate. I'm going to leave this for now and put in another pull request soon where I'll use the ThrottlePublisher class to set a rate for each thing that the bridge is publishing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52)*

**Comment by dcrossman** [comment]
So I updated the simulator bridge to use throttled publishers and individual rates. That branch includes these changes. Do you guys want me to just update this branch with the changes or make a new pull request @irwineffect  @bkallaher?

**Comment by irwineffect** [comment]
:lgtm:

---

Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-:-KbNZA5BQrfx6k_NZxzi:bnfp4nl)*

**Comment by bkallaher** [comment]
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[models/cobalt/model.sdf, line 798 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KbCNUSay2mnXGP1xJRA:-KbN_PNRTFz6cwOfhies:bsqv5bi) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/8e8570caf627ae680483418c0b1fac35900b08f1/models/cobalt/model.sdf#L798)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

The bno's update rate is set to 20 in cobalt.param.
</blockquote></details>

Looks Good

---

*[param/simulator.yaml, line 6 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52#-KbCT-Ef1AL-n88vMm3v:-KbN_RNUViatd0gOFf2K:bsqv5bi) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/8e8570caf627ae680483418c0b1fac35900b08f1/param/simulator.yaml#L6)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

Ok so this is currently the global bridge rate. I'm going to leave this for now and put in another pull request soon where I'll use the ThrottlePublisher class to set a rate for each thing that the bridge is publishing.
</blockquote></details>

Looks Good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52)*

**Comment by bkallaher** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/52)*

**Pull request merged**
