### PR TITLE
Torpedo shooter gazebo plugin

### PR DESCRIPTION
**Pull request by brennanpeter**
A creates a ros service (/shoot_torpedo) that will spawn a simple torpedo box beneath the sub and fire it in the direction of the sub is currently facing.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/102)

### CODE REVIEW

**Comment by irwineffect** [comment]
:lgtm: This is freaking sweet! 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/102#-:-KxKNWluRa7kf8ylhbDO:b-4pl70v)*

**Comment by skallaher** [comment]
@brennanpeter, please fix the linter errors on this PR so that it can be completed.

**Comment by skallaher** [comment]
Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/torpedo_shooter.cpp, line 37 at r2](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/102#-L-5PttQe7vGocH8iADV:-L-5PttQe7vGocH8iADW:b-vj2x5p) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/233db866f2fa35ef5006ac3d9306756bdfc58cf0/src/torpedo_shooter.cpp#L37)):*
> ```cpp
>     // the torpedo
>     // Using just trig
>     math::Vector3 magnitude = \
> ```

This is C++, not Python. You don't need these to move to a new line. Ditto on others.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/102)*

**Comment by skallaher** [comment]
:lgtm:

---

Review status: 4 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/102#-:-L-8sZWXhsYPIvuq4N8X:bnfp4nl)*

**Comment by skallaher** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/102)*

**Comment by skallaher** [comment]
Reviewed 4 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/102)*

**Comment by skallaher** [comment]
Reviewed 1 of 2 files at r2.
Review status: 5 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/102)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/102)*

**Pull request merged**
