### PR TITLE
Add in vritual serial port control and polynomialized thrust

### PR DESCRIPTION
**Pull request by ryan-summers**
This commit creates more realistically simulated thrusters. (Woohoo!)

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/59)

### CODE REVIEW

**Comment by irwineffect** [comment]
could you also make it so the thruster visualization doesn't show up when we send zeros? Also give it a one-second timeout.

---

Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/maestro_emulator.cpp, line 85 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-KbmGlMDBF6KiZYH73B5:-KbmGlMDBF6KiZYH73B6:bnhqsn2) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/1d65d14e4bc7cdacdea36210d189e90a54004d18/src/maestro_emulator.cpp#L85)):*
> ```cpp
>                     d_negative;
>     }
>     else if ((pulse_length > 1475))
> ```

The greater than and less than signs on this conditional are both reversed. Also, double parenthesis

---

*[src/maestro_emulator.cpp, line 94 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-KbmGqJpbSkq899KiQdH:-KbmGqJpbSkq899KiQdI:b-hu314a) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/1d65d14e4bc7cdacdea36210d189e90a54004d18/src/maestro_emulator.cpp#L94)):*
> ```cpp
>     else
>     {
>         force_kgf = 0;
> ```

Return zero here to ensure that an improper zero floating point comparison doesn't occur, which results in minimum force being applied instead.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-:-KbmHfpoUJWCFn3tgVF_:b-a9xvzl)*

**Comment by ryan-summers** [comment]
Review status: 0 of 12 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/maestro_emulator.cpp, line 85 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-KbmGlMDBF6KiZYH73B5:-KbmU6IRt1LauFYxRLWO:b-896fix) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/1d65d14e4bc7cdacdea36210d189e90a54004d18/src/maestro_emulator.cpp#L85)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

The greater than and less than signs on this conditional are both reversed. Also, double parenthesis
</blockquote></details>

Done.

---

*[src/maestro_emulator.cpp, line 94 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-KbmGqJpbSkq899KiQdH:-KbmU70q-fbkt5ISPdAa:b-896fix) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/1d65d14e4bc7cdacdea36210d189e90a54004d18/src/maestro_emulator.cpp#L94)):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Return zero here to ensure that an improper zero floating point comparison doesn't occur, which results in minimum force being applied instead.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59)*

**Comment by irwineffect** [comment]
I'm seeing some really crazy behavior with this latest revision, the sub won't even hold depth properly. Can you verify this works?

---

Reviewed 9 of 12 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-:-Kbpjo4qjTu2-7GO8dPF:b-hm4qkf)*

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-Kbpu_WPBRlEyQx1IchZ:-Kbpu_WPBRlEyQx1Ich_:b-hm4qkf) (no related file):*
I'm seeing some really crazy behavior with this latest revision, the sub won't even hold depth properly. Can you verify this works?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-Kbpu_WPBRlEyQx1IchZ:-KbpzF8JJcBzWi5PREIg:b-r66hhj) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

I'm seeing some really crazy behavior with this latest revision, the sub won't even hold depth properly. Can you verify this works?
</blockquote></details>

I tested it all before I even committed it. I can come by the lab around 2 PM and look at what you're seeing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59)*

**Comment by ryan-summers** [comment]
Review status: 11 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-Kbpu_WPBRlEyQx1IchZ:-Kbs5-yM-qT04Uw6ygWA:b2l2uuv) (no related file):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

I tested it all before I even committed it. I can come by the lab around 2 PM and look at what you're seeing.
</blockquote></details>

Should be corrected now!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59)*

**Comment by dcrossman** [comment]
Review status: 11 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/serial.cpp, line 103 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-KbxI2X-RJJTQ_APH3Ms:-KbxI2X1D1TqCq_3TvM0:b2530jt) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/a4584e631df3b9cf5dbe10d8573fbf78cdb27dd7/src/serial.cpp#L103)):*
> ```cpp
>             if (i < 0)
>             {
>                 ROS_ERROR("serial write error");
> ```

This should be ROS_ERROR_THROTTLE since it can easily flood the output when the simulator is killed.

---

*[src/thruster_plugin.cpp, line 20 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-KbxSWpNhdwRSJA52y_J:-KbxSWpNhdwRSJA52y_K:b-43u4eg) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/a4584e631df3b9cf5dbe10d8573fbf78cdb27dd7/src/thruster_plugin.cpp#L20)):*
> ```cpp
> 
>     XmlRpc::XmlRpcValue thruster_settings;
>     if(!ros::param::get("thrusters", thruster_settings))
> ```

Should be thrusters/mapping

---

*[src/thruster_plugin.cpp, line 27 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-KbvmaYs9Fu5XJckgkZg:-KbvmaYs9Fu5XJckgkZh:bxfry7d) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/a4584e631df3b9cf5dbe10d8573fbf78cdb27dd7/src/thruster_plugin.cpp#L27)):*
> ```cpp
> 
>     double max_thrust = 0;
>     if (!ros::param::get("control/max_thrust", max_thrust))
> ```

Should be thrusters/max_thrust

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59)*

**Comment by dcrossman** [comment]
Review status: 11 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-Kbpu_WPBRlEyQx1IchZ:-KbxaKYKd8R2yVHGmJsX:bfeqkg6) (no related file):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

Should be corrected now!
</blockquote></details>

I don't know what James was seeing but I'm seeing a lack of behavior currently. When I run everything in the simulator control messages don't seem to work (only the force from the buoyancy compensation is being outputted so the sub just sits on the bottom). (oh also this is after I fixed the lines I made comments on). I'm not really sure what's up but I'm still looking.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59)*

**Comment by dcrossman** [comment]
Review status: 11 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-Kbpu_WPBRlEyQx1IchZ:-KbxbzrW03AgLubEfAAq:b-nkgfhv) (no related file):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

I don't know what James was seeing but I'm seeing a lack of behavior currently. When I run everything in the simulator control messages don't seem to work (only the force from the buoyancy compensation is being outputted so the sub just sits on the bottom). (oh also this is after I fixed the lines I made comments on). I'm not really sure what's up but I'm still looking.
</blockquote></details>

Ok ignore all that ^. An instance of create_thruster_vsp had not gotten killed so it never cleaned up the ports.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59)*

**Comment by ryan-summers** [comment]
Review status: 9 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/serial.cpp, line 103 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-KbxI2X-RJJTQ_APH3Ms:-Kc-5l3f7BntoS3AoTxW:b-oz8tym) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/a4584e631df3b9cf5dbe10d8573fbf78cdb27dd7/src/serial.cpp#L103)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

This should be ROS_ERROR_THROTTLE since it can easily flood the output when the simulator is killed.
</blockquote></details>

Good call.

---

*[src/thruster_plugin.cpp, line 20 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-KbxSWpNhdwRSJA52y_J:-Kc-6-_QZ8txpI9ZFsXh:b-e607z5) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/a4584e631df3b9cf5dbe10d8573fbf78cdb27dd7/src/thruster_plugin.cpp#L20)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

Should be thrusters/mapping
</blockquote></details>

Good call. I updated the mapping in robosub but forgot to update it here.

---

*[src/thruster_plugin.cpp, line 27 at r3](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-KbvmaYs9Fu5XJckgkZg:-Kc-6KQqpAu0zG8vZ8be:b-j1q3po) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/a4584e631df3b9cf5dbe10d8573fbf78cdb27dd7/src/thruster_plugin.cpp#L27)):*
<details><summary><i>Previously, BigDCross (Dustin Crossman) wrote…</i></summary><blockquote>

Should be thrusters/max_thrust
</blockquote></details>

Ditto as above. Corrected!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59)*

**Comment by dcrossman** [comment]
Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59)*

**Comment by dcrossman** [comment]
Reviewed 7 of 12 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/59#-:-KcAGhmMEWfcIg-hA2rv:bnfp4nl)*

**Pull request merged**
