### PR TITLE
Alison/models

### PR DESCRIPTION
**Pull request by AlisonB319**
This is the world for the qualification test. The new gate and new pole use the code from the previous gate and pole with updated dimensions and colors. The new world has the sub, gate, and pole in the locations specified by the instructions with the current location of the sub as the Start Point.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/106)

### CODE REVIEW

**Comment by Sindorman** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/106#-:-L-mHNtM1yJwH40Y08mu:bnfp4nl)*

**Comment by Sindorman** [comment]
It did though said that PR is out of date

**Comment by irwineffect** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/106#-L-n7ox89R8dmlz6yBGd:-L-n7ox89R8dmlz6yBGe:bhty4c2) (no related file):*
Looking at `gibb_qualification.world`, I'm guessing that you placed the objects within Gazebo and then saved the world file? 
This resulted in the file being 1603 lines long, for context our existing world files are <300 lines long. It seems Gazebo saved a bunch of extra information in that world file that we probably don't want.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/106#-L-nArzhFAv70S24z4L7:-L-nArzhFAv70S24z4L8:b734685) (no related file):*
On second thought, I think it might be a good idea to call "new_gate" the "qualification_gate", it's a lot more descriptive.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/106)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/106#-L-n7ox89R8dmlz6yBGd:-L1TV-85GKPs2E7yyAEG:b-v2lv52) (no related file):*
<details><summary><i>Previously, irwineffect wrote…</i></summary><blockquote>

Looking at `gibb_qualification.world`, I'm guessing that you placed the objects within Gazebo and then saved the world file? 
This resulted in the file being 1603 lines long, for context our existing world files are <300 lines long. It seems Gazebo saved a bunch of extra information in that world file that we probably don't want.
</blockquote></details>

It looks like the file actually has the model descriptions inside of it instead of <include>'ing the URI for the models like we do in gibb.world.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/106)*

**Comment by skallaher** [comment]
This PR is going on ice for now as we don't immediately need these models.

**Pull request closed without merging**
