### PR TITLE
Added launching of bottom camera undistortion for Roulette AI

### PR DESCRIPTION
**Pull request by ryan-summers**
The bottom camera undistortion is used by the Roulette AI for slice detection. This change adds in calibration parameters for the downward facing camera and causes it to be launched on startup.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/117)

### CODE REVIEW

**Comment by skallaher** [comment]
Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[launch/gazebo.launch, line 35 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/117#-L4D6zCN_VzlvoNMXxjz:-L4D6zCN_VzlvoNMXxk-:b-f5lfqv) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/d2e048579d559e95da57528c927cc76ca1f3a65a/launch/gazebo.launch#L35)):*
> ```XML
>     <param name="camera" value="bottom"/>
>     <rosparam command="load" file="$(find robosub_simulator)/param/bottom_camera.yaml" />
>   </node>
> ```

Will we need to add the left and right cameras here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/117)*

**Comment by skallaher** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/117)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[launch/gazebo.launch, line 35 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/117#-L4D6zCN_VzlvoNMXxjz:-L4DCRP1v3qqOCNXgryC:b-4zkb7o) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/d2e048579d559e95da57528c927cc76ca1f3a65a/launch/gazebo.launch#L35)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Will we need to add the left and right cameras here?
</blockquote></details>

I don't think anything else currently relies on undistorted images. The only thing that would is the vision network, but that is launched with the sim_vision_network node. We could launch undistorted cameras if the vision network is not simulated?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/117)*

**Comment by skallaher** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[launch/gazebo.launch, line 35 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/117#-L4D6zCN_VzlvoNMXxjz:-L4DD20Mcl95esIubFfg:b-kyhppk) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/d2e048579d559e95da57528c927cc76ca1f3a65a/launch/gazebo.launch#L35)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

I don't think anything else currently relies on undistorted images. The only thing that would is the vision network, but that is launched with the sim_vision_network node. We could launch undistorted cameras if the vision network is not simulated?
</blockquote></details>

I can't think of anything at the moment. :lgtm:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/117)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/117#-:-L4JvKDgLBSobmyPuMUP:bnfp4nl)*

**Pull request merged**
