### PR TITLE
Adds in fake vision network

### PR DESCRIPTION
**Pull request by ryan-summers**
The fake vision network may be used under the following scenarios:
1) User does not have NVidia cards
2) The network is not trained on certain props
3) Vision data needs to be labelled for training

The tool utilizes the gazebo/link_states topic and passes the points through the appropriate image filtering algorithms to determine the bounding box of objects.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/110)

### CODE REVIEW

**Comment by Sindorman** [comment]
Can you describe to me without all the details on how it works? I mean for example does it properly translates a box put on object at different angles?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-:-L1duBI3HvINE1kra2BB:b8a6aby)*

**Comment by ryan-summers** [comment]
Yes. This program will always properly draw a bounding box around any orientation/angled object. Below is an explanation of the 3D mathematics of how this is done.

All the details - \

Flow of information:
1) The program receives the link_state of the left_camera and obstacles in the pool.
2) A 3D bounding box is drawn around obstacles based on provided width, height, and depth params.
2) Program converts the coordinates of obstacles and their bounding vertices to be from the frame of reference to the camera.
3) The 3D coordinates are mapped onto the fisheye lens of the camera.
4) The mapped coordinates then go through the same process that the undistortion node applies, which means they are identical to coordinates on the undistorted image.
5) A bounding box is drawn around the coordinates.
6) DetectionArray message is published.

**Comment by daymare** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-:-L1e1HssElaqCDK6F8B5:bnfp4nl)*

**Comment by daymare** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110)*

**Comment by Sindorman** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-:-L3FehnWlkwAmDbJRWq7:bnfp4nl)*

**Comment by skallaher** [comment]
Reviewed 4 of 5 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks broke.

---

*[param/left_calibration.json, line 1 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZKId25ZvjEcr8wdJB:-L3ZKId25ZvjEcr8wdJC:b-8mlatc) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/param/left_calibration.json#L1)):*
> ```JSON
> {
> ```

Is there a reason you're using json here rather than yaml?

---

*[param/simulator.yaml, line 26 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZMGJBLVM1K0UDJ2yI:-L3ZMGJBLVM1K0UDJ2yJ:b-d041nv) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/param/simulator.yaml#L26)):*
> ```YAML
>             height: 1.5
>             width: 0.1
>             depth: 0.1
> ```

This set of parameters feels a bit long-winded, is it possible to make these more concise?

---

*[scripts/sim_vision_network.py, line 61 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZLda4lOuOZ7M2w74c:-L3ZLda4lOuOZ7M2w74d:br69eee) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/scripts/sim_vision_network.py#L61)):*
> ```Python
> 
> 
> lens_parameters = FisheyeLens(c1=685.4, c2=525.2, c3=0, f=307.53251966606937)
> ```

Where are these default parameters coming from?

---

*[scripts/sim_vision_network.py, line 64 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZLoBOvpGKquXsTSR2:-L3ZLoBOvpGKquXsTSR3:bnktp8z) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/scripts/sim_vision_network.py#L64)):*
> ```Python
> 
> 
> class Point:
> ```

Why not use a 3-tuple?

---

*[scripts/sim_vision_network.py, line 178 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZNqSGtM3qHIBsn7Du:-L3ZNqSGtM3qHIBsn7Dv:bq59mh7) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/scripts/sim_vision_network.py#L178)):*
> ```Python
> 
> 
> def change_reference_frame(point, rot_quat, origin):
> ```

FYI, utilizing TF's tool set would make this function and quite a few others here unnecessary and possibly easier to use. The SD team has already done some work with publishing TF frames using links from gazebo.

---

*[scripts/sim_vision_network.py, line 467 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZOpjcVqiocAvkZY5F:-L3ZOpjcVqiocAvkZY5G:bwwtlbw) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/scripts/sim_vision_network.py#L467)):*
> ```Python
> 
> if __name__ == '__main__':
>     rospy.init_node('fake_network', anonymous=True)
> ```

Is there a reason this is anonymous? You already modify the name in the launch file.

---

*[scripts/sim_vision_network.py, line 473 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZP8nNusdax3iacKQX:-L3ZP8nNusdax3iacKQY:btv5jyp) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/scripts/sim_vision_network.py#L473)):*
> ```Python
> 
>     debug = rospy.get_param('~debug', default=False)
>     max_distance = rospy.get_param('~max_disatance', default=10)
> ```

`distance` rather than `disatance`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110)*

**Comment by ryan-summers** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[param/left_calibration.json, line 1 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZKId25ZvjEcr8wdJB:-L3ouW-FZwia1veQO1BK:b-vks51m) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/param/left_calibration.json#L1)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Is there a reason you're using json here rather than yaml?
</blockquote></details>

This is the format that I wrote the calibration script to export in. I can update both if you would like. YAML definitely has its perks.

---

*[param/simulator.yaml, line 26 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZMGJBLVM1K0UDJ2yI:-L3oub_wL5Qyu9tKNdww:b-ams2o1) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/param/simulator.yaml#L26)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

This set of parameters feels a bit long-winded, is it possible to make these more concise?
</blockquote></details>

There may be a way to grab the link geometry from Gazebo, but that may be more complicated. These are all the required pieces of information for a label.

---

*[scripts/sim_vision_network.py, line 61 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZLda4lOuOZ7M2w74c:-L3oul9TnVv8UV0Tk45e:bstjo0r) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/scripts/sim_vision_network.py#L61)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Where are these default parameters coming from?
</blockquote></details>

They come from the characteristics of the fisheye camera model that we have in the cobalt SDF model.

---

*[scripts/sim_vision_network.py, line 64 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZLoBOvpGKquXsTSR2:-L3ouqGeaPg_9MGi8K9w:b-32cj06) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/scripts/sim_vision_network.py#L64)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Why not use a 3-tuple?
</blockquote></details>

I wanted access to the parameters in x, y, and z notation.

---

*[scripts/sim_vision_network.py, line 467 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZOpjcVqiocAvkZY5F:-L3ov35iZZYBsgkHL9H6:bp9o6jg) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/scripts/sim_vision_network.py#L467)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Is there a reason this is anonymous? You already modify the name in the launch file.
</blockquote></details>

It needs to run on both the left and right cameras (as per stereo vision requirements)

---

*[scripts/sim_vision_network.py, line 473 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZP8nNusdax3iacKQX:-L3ov6b6eIWGZiFFAeZJ:b7anmnw) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/scripts/sim_vision_network.py#L473)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

`distance` rather than `disatance`
</blockquote></details>

good call

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/sim_vision_network.py, line 61 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZLda4lOuOZ7M2w74c:-L3ovf68JWQi6H3p2-mt:b60wta3) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/scripts/sim_vision_network.py#L61)):*
<details><summary><i>Previously, ryan-summers (Ryan Summers) wrote…</i></summary><blockquote>

They come from the characteristics of the fisheye camera model that we have in the cobalt SDF model.
</blockquote></details>

Could you put a comment above this to denote where these are in that SDF?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110)*

**Comment by ryan-summers** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/sim_vision_network.py, line 178 at r6](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110#-L3ZNqSGtM3qHIBsn7Du:-L3oygWk0BBlPPvar_5v:b-896fix) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b9cd1a3cadd2874568c12c18b0f44f819e1864c8/scripts/sim_vision_network.py#L178)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

FYI, utilizing TF's tool set would make this function and quite a few others here unnecessary and possibly easier to use. The SD team has already done some work with publishing TF frames using links from gazebo.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/110)*

**Pull request merged**
