### PR TITLE
Modified simulated vision network to use standard camera parameter file

### PR DESCRIPTION
**Pull request by ryan-summers**
This change is for conformity with the calibrate.py script and with the vision changes introduced in the main robosub repository.

---
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/118)

### CODE REVIEW

**Comment by skallaher** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[scripts/sim_vision_network.py, line 477 at r1](https://beta.reviewable.io/reviews/palouserobosub/robosub_simulator/118#-L4IGP9I7v4hB0l9Dwej:-L4IGP9I7v4hB0l9Dwek:b-c56w6y) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b7993800d199a7d0f44cec2a885c5b43d9bf9b3a/scripts/sim_vision_network.py#L477)):*
> ```Python
>     print K
>     print D
>     print image_size
> ```

Is there a reason you are printing these out? If so, they should be rospy.log<level> calls instead of print calls.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/palouserobosub/robosub_simulator/118)*

**Comment by ryan-summers** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[scripts/sim_vision_network.py, line 477 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/118#-L4IGP9I7v4hB0l9Dwej:-L4JvWLXWVauSCvUFgtp:b-jpw1pj) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/b7993800d199a7d0f44cec2a885c5b43d9bf9b3a/scripts/sim_vision_network.py#L477)):*
<details><summary><i>Previously, skallaher (Sean Kallaher) wrote…</i></summary><blockquote>

Is there a reason you are printing these out? If so, they should be rospy.log<level> calls instead of print calls.
</blockquote></details>

I removed them - It was a holdover from debugging.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/118)*

**Comment by skallaher** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/palouserobosub/robosub_simulator/118#-:-L4Jvimh3z8NzsK3Vfw6:bnfp4nl)*

**Comment by skallaher** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/118)*

**Pull request merged**
