### PR TITLE
Couple fixes to obstacle position publisher.

### PR DESCRIPTION
**Pull request by dcrossman**
This change is [Reviewable](https://reviewable.io/reviews/palouserobosub/robosub_simulator/64)

### CODE REVIEW

**Comment by bkallaher** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/simulator_bridge.cpp, line 221 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/64#-Kd3BQn71WQvTj7SZKo1:-Kd3BQn71WQvTj7SZKo2:bxv6f98) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/c515d1fba09b1550cb73ba6d3600cc8b47542a39/src/simulator_bridge.cpp#L221)):*
> ```cpp
>             // Extract necessary data from modelstates.
>             robosub::ObstaclePos pos;
>             pos.x = msg.pose[idx].position.x - pinger_position[0];
> ```

Is there really a reason to be publishing this data on a topic?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/64)*

**Comment by dcrossman** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/simulator_bridge.cpp, line 221 at r1](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/64#-Kd3BQn71WQvTj7SZKo1:-Kd3ybVMjTOsFV5qASB3:bmhdy4y) ([raw file](https://github.com/palouserobosub/robosub_simulator/blob/c515d1fba09b1550cb73ba6d3600cc8b47542a39/src/simulator_bridge.cpp#L221)):*
<details><summary><i>Previously, bkallaher wrote…</i></summary><blockquote>

Is there really a reason to be publishing this data on a topic?
</blockquote></details>

Yea I'd like to have it for now for localization (faking vision output and stuff). It might be useful for unit testing as well. We can always get rid of it later since it is technically redundant because of the ModelStates publisher. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/64)*

**Comment by bkallaher** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/64)*

**Comment by irwineffect** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/palouserobosub/robosub_simulator/64#-:-KdX_U7Er4QCNtNi2meQ:bnfp4nl)*

**Pull request merged**
