### PR TITLE
Mesh conversions

### PR DESCRIPTION
**Pull request by bkallaher**
#7 is solved with this pull request. Both the buoys and the gate have been converted to sdf only models. most gazebo colors have the diffusion overridden for better looking visuals.

### CODE REVIEW

**Comment by bkallaher** [comment]
Looking at the dimensions in the rules the original model was a bit off. I'm working on updating them now.

**Review by irwineffect — COMMENTED** [review]
The lower half of the gate is really dark, is there a shadow or something causing this?

**Comment by bkallaher** [comment]
Yes that is a shadow.

**Comment by irwineffect** [comment]
Can you fix it?

**Comment by bkallaher** [comment]
Maybe.

**Comment by bkallaher** [comment]
The only way I could get the shadows to go away was to completely disable them in the world. Do we want them at all?

**Review by irwineffect — APPROVED** [review]
looks good!

**Pull request merged**
